package net.oekora;


import fish.payara.micro.BootstrapException;
import fish.payara.micro.PayaraMicro;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Server {

    public static void main(String... args) throws BootstrapException {

        System.out.println("Hello, World!");
        PayaraMicro.getInstance()
                .addDeployment(args[0])
                //.setHttpPort(8080)  // default port is 8080
                .bootStrap();
    }
}
