
import fish.payara.micro.BootstrapException;
import fish.payara.micro.PayaraMicro;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {

    public static void main(String... args) throws BootstrapException {

        System.out.println("Hello, World!");
        PayaraMicro.getInstance().setHttpPort(8080).bootStrap();
    }
}
