package net.oekora;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ServerTest {

    @Test public void testSomeLibraryMethod() {
        Server classUnderTest = new Server();
        //assertThat("someLibraryMethod should return 'true'", classUnderTest.main());
    }
}
